services:
  superset:
    build:
      context: .
      dockerfile: Dockerfile
    image: superset
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_ADMIN_USERNAME: "admin"
      SUPERSET_ADMIN_PASSWORD: "admin"
      SUPERSET_SECRET_KEY: "supersecretkey"
    volumes:
      - ./docker_volumes/superset_home:/app/superset_home
    depends_on:
      - postgres
    networks:
      - superset-net

  postgres:
    image: postgres:15
    container_name: superset-postgres
    environment:
      POSTGRES_USER: "superset"
      POSTGRES_PASSWORD: "superset"
      POSTGRES_DB: "superset"
    volumes:
      - ./docker_volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - superset-net
    ports:
      - "5432:5432"

networks:
  superset-net:
    driver: bridge
