services:
  superset:
    build:
      context: .
    image: superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    restart: always
    env_file:
      - .env
    volumes:
      - ./volumes/superset_home:/app/superset_home
    depends_on:
      - postgres
    networks:
      - superset-net

  postgres:
    image: postgres:16
    container_name: superset-postgres
    env_file:
      - .env
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - superset-net
    ports:
      - "5432:5432"
    restart: always

networks:
  superset-net:
    driver: bridge
